package com.mycompany.bp_lab_proje_burak_erdogan;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thebu
 */
public class KULLANICI_KAYIT extends javax.swing.JFrame {

    /**
     * Creates new form KULLANİCİ_KAYİT
     */
    public KULLANICI_KAYIT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_kullaniciadi_2 = new javax.swing.JLabel();
        txt_adSoyad_oyuncu_2 = new javax.swing.JTextField();
        lbl_KayitEkrani_KullaniciAD_2 = new javax.swing.JLabel();
        txt_kullaniciMAIL_kayitEkran_oyuncu_2 = new javax.swing.JTextField();
        txt_KullaniciSifre_kayitEkran_oyuncu_2 = new javax.swing.JPasswordField();
        lbl_GirisEkrani_Sifre_2 = new javax.swing.JLabel();
        lbl_yenidenparola_2 = new javax.swing.JLabel();
        txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2 = new javax.swing.JPasswordField();
        btn_kayit_Olundu = new javax.swing.JButton();
        lbl_kayitEkrani_oyuncu_2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_iptal = new javax.swing.JButton();
        lbl_kullaniciadi_1 = new javax.swing.JLabel();
        lbl_KayitEkrani_KullaniciAD1 = new javax.swing.JLabel();
        lbl_GirisEkrani_Sifre_1 = new javax.swing.JLabel();
        lbl_yenidenparola_1 = new javax.swing.JLabel();
        txt_adSoyad_oyuncu_1 = new javax.swing.JTextField();
        txt_kullaniciMAIL_kayitEkran_oyuncu_1 = new javax.swing.JTextField();
        txt_KullaniciSifre_kayitEkran_oyuncu_1 = new javax.swing.JPasswordField();
        txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1 = new javax.swing.JPasswordField();
        lbl_kayitEkrani_oyuncu_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KAYIT EKRANI");
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lbl_kullaniciadi_2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_kullaniciadi_2.setText("Adiniz Soyadiniz : ");

        lbl_KayitEkrani_KullaniciAD_2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_KayitEkrani_KullaniciAD_2.setText("Kullanici Maili");

        lbl_GirisEkrani_Sifre_2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_GirisEkrani_Sifre_2.setText("Parola : ");

        lbl_yenidenparola_2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_yenidenparola_2.setText("Yeniden Parola : ");

        btn_kayit_Olundu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_kayit_Olundu.setText("Kayit Ol");
        btn_kayit_Olundu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayit_OlunduActionPerformed(evt);
            }
        });

        lbl_kayitEkrani_oyuncu_2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_kayitEkrani_oyuncu_2.setText("OYUNCU 2 KAYİT EKRANİ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kayit_Olundu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_yenidenparola_2)
                                .addGap(66, 66, 66)
                                .addComponent(txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_kullaniciadi_2)
                                        .addGap(53, 53, 53))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_KayitEkrani_KullaniciAD_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(54, 54, 54))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_GirisEkrani_Sifre_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kullaniciMAIL_kayitEkran_oyuncu_2)
                                    .addComponent(txt_adSoyad_oyuncu_2)
                                    .addComponent(txt_KullaniciSifre_kayitEkran_oyuncu_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_kayitEkrani_oyuncu_2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_kayitEkrani_oyuncu_2)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kullaniciadi_2)
                    .addComponent(txt_adSoyad_oyuncu_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_KayitEkrani_KullaniciAD_2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kullaniciMAIL_kayitEkran_oyuncu_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KullaniciSifre_kayitEkran_oyuncu_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_GirisEkrani_Sifre_2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_yenidenparola_2)
                    .addComponent(txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btn_kayit_Olundu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        btn_iptal.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_iptal.setText("Iptal");
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });

        lbl_kullaniciadi_1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_kullaniciadi_1.setText("Adiniz Soyadiniz : ");

        lbl_KayitEkrani_KullaniciAD1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_KayitEkrani_KullaniciAD1.setText("Kullanici Maili");

        lbl_GirisEkrani_Sifre_1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_GirisEkrani_Sifre_1.setText("Parola : ");

        lbl_yenidenparola_1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_yenidenparola_1.setText("Yeniden Parola : ");

        lbl_kayitEkrani_oyuncu_1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_kayitEkrani_oyuncu_1.setText("OYUNCU 1 KAYİT EKRANİ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_iptal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_kayitEkrani_oyuncu_1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_GirisEkrani_Sifre_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_KayitEkrani_KullaniciAD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_kullaniciadi_1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(lbl_yenidenparola_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(50, 50, 50)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_adSoyad_oyuncu_1)
                                .addComponent(txt_kullaniciMAIL_kayitEkran_oyuncu_1)
                                .addComponent(txt_KullaniciSifre_kayitEkran_oyuncu_1)
                                .addComponent(txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_kayitEkrani_oyuncu_1)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kullaniciadi_1)
                    .addComponent(txt_adSoyad_oyuncu_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_KayitEkrani_KullaniciAD1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kullaniciMAIL_kayitEkran_oyuncu_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_GirisEkrani_Sifre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_KullaniciSifre_kayitEkran_oyuncu_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_yenidenparola_1)
                    .addComponent(txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_iptal)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayit_OlunduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayit_OlunduActionPerformed
        // TODO add your handling code here:

        if (this.txt_kullaniciMAIL_kayitEkran_oyuncu_2.getText().isEmpty() || this.txt_KullaniciSifre_kayitEkran_oyuncu_2.getText().isEmpty() || this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2.getText().isEmpty() || this.txt_adSoyad_oyuncu_2.getText().isEmpty()
                || this.txt_kullaniciMAIL_kayitEkran_oyuncu_1.getText().isEmpty() || this.txt_KullaniciSifre_kayitEkran_oyuncu_1.getText().isEmpty() || this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1.getText().isEmpty() || this.txt_adSoyad_oyuncu_1.getText().isEmpty()) {
            //her kismin bos olup olmadigi kontrolu
            JOptionPane.showMessageDialog(rootPane, " Lutfen Tum Bosluklari Doldurunuz ", "Dikkat!!", JOptionPane.INFORMATION_MESSAGE);

        } else {

            if (this.txt_kullaniciMAIL_kayitEkran_oyuncu_1.getText().equals(this.txt_kullaniciMAIL_kayitEkran_oyuncu_2.getText())) {
                //ayni maili kullanip kullanilmadigi kontrolu
                JOptionPane.showMessageDialog(rootPane, "Ayni Mail 2 Defa Kullanilamaz!!", "Dikkat!!", JOptionPane.ERROR_MESSAGE);
                this.txt_kullaniciMAIL_kayitEkran_oyuncu_2.setText("");

            } else {
                // sifrenin  6  haneden az olup olmadigi kontrolu
                if (this.txt_KullaniciSifre_kayitEkran_oyuncu_2.getText().length() < 6 || this.txt_KullaniciSifre_kayitEkran_oyuncu_1.getText().length() < 6) {

                    if (this.txt_KullaniciSifre_kayitEkran_oyuncu_2.getText().length() < 6) {
                        JOptionPane.showMessageDialog(rootPane, " Oyuncu 2 Lutfen Sifreniz En Az 6 Haneden Olusmalidir!! ", "DIKKAT!!", JOptionPane.ERROR_MESSAGE);
                        this.txt_KullaniciSifre_kayitEkran_oyuncu_2.setText("");
                        this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2.setText("");
                    } else if (this.txt_KullaniciSifre_kayitEkran_oyuncu_1.getText().length() < 6) {
                        JOptionPane.showMessageDialog(rootPane, " Oyuncu 1 Lutfen Sifreniz En Az 6 Haneden Olusmalidir!! ", "DIKKAT!!", JOptionPane.ERROR_MESSAGE);
                        this.txt_KullaniciSifre_kayitEkran_oyuncu_1.setText("");
                        this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1.setText("");

                    }
                } else {
                    // eger iki sifrede uyusursa kisileri kaydediyorum ve dosyaya yazdiriyorum
                    if (this.txt_KullaniciSifre_kayitEkran_oyuncu_2.getText().equals(this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2.getText()) && this.txt_KullaniciSifre_kayitEkran_oyuncu_1.getText().equals(this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1.getText())) {

                        Kullanici kullanici = new Kullanici();
                        Kullanici kullanici2 = new Kullanici();

                        kullanici2.ad_soyad = this.txt_adSoyad_oyuncu_2.getText();
                        kullanici2.kullaniciMail = this.txt_kullaniciMAIL_kayitEkran_oyuncu_2.getText();
                        kullanici2.parola = this.txt_KullaniciSifre_kayitEkran_oyuncu_2.getText();

                        kullanici.ad_soyad = this.txt_adSoyad_oyuncu_1.getText();
                        kullanici.kullaniciMail = this.txt_kullaniciMAIL_kayitEkran_oyuncu_1.getText();
                        kullanici.parola = this.txt_KullaniciSifre_kayitEkran_oyuncu_1.getText();

                        try {
                            Veriler.kullaniciEkle(kullanici);

                            Veriler.DosyayaYazdir();
                            Veriler.kullaniciEkle(kullanici2);
                            Veriler.DosyayaYazdir();

                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(rootPane, "Bu E-Mail Kayitlidir!!!", "Dikkat", JOptionPane.ERROR_MESSAGE);
                        }

                        JOptionPane.showMessageDialog(rootPane, " 2 Oyuncuda Basariyla Kayit Olundu ", "BILGILENDRIME", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();

                        KULLANICI_GIRIS giris = new KULLANICI_GIRIS();
                        //diger frame i ekrana veriyorum tekrardan
                        giris.setVisible(true);

                    } else {

                        if (!this.txt_KullaniciSifre_kayitEkran_oyuncu_2.getText().equals(this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2.getText())) {
                            // esit olmayan kisimlari sifirliyorum
                            JOptionPane.showMessageDialog(rootPane, " Oyuncu 2 Sifreleriniz Uyusmamaktadir Lutfen Dogru Bir Sekilde Tekrar Giriniz", "DIKKAT!!", JOptionPane.ERROR_MESSAGE);
                            this.txt_KullaniciSifre_kayitEkran_oyuncu_2.setText("");
                            this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2.setText("");
                        } else if (!this.txt_KullaniciSifre_kayitEkran_oyuncu_1.getText().equals(this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1.getText())) {
                            JOptionPane.showMessageDialog(rootPane, " Oyuncu 1 Sifreleriniz Uyusmamaktadir Lutfen Dogru Bir Sekilde Tekrar Giriniz", "DIKKAT!!", JOptionPane.ERROR_MESSAGE);
                            this.txt_KullaniciSifre_kayitEkran_oyuncu_1.setText("");
                            this.txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1.setText("");
                        }

                    }

                }

            }

        }


    }//GEN-LAST:event_btn_kayit_OlunduActionPerformed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
        // TODO add your handling code here:
        //iptal butonu
        this.dispose();
        KULLANICI_GIRIS giris = new KULLANICI_GIRIS();
        giris.setVisible(true);

    }//GEN-LAST:event_btn_iptalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KULLANICI_KAYIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KULLANICI_KAYIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KULLANICI_KAYIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KULLANICI_KAYIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KULLANICI_KAYIT().setVisible(true);
            }
        });
    }

    public String getLbl_kullaniciadi_1() { // bu kisimda ise burdaki isimleri oyun ekranina gonderiyorum
        String kullaniciAdi1 = this.txt_adSoyad_oyuncu_1.getText().trim();
        return kullaniciAdi1;
    }

    public String getLbl_kullaniciadi_2() {
        String kullaniciAdi2 = this.txt_adSoyad_oyuncu_2.getText().trim();
        return kullaniciAdi2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iptal;
    private javax.swing.JButton btn_kayit_Olundu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_GirisEkrani_Sifre_1;
    private javax.swing.JLabel lbl_GirisEkrani_Sifre_2;
    private javax.swing.JLabel lbl_KayitEkrani_KullaniciAD1;
    private javax.swing.JLabel lbl_KayitEkrani_KullaniciAD_2;
    private javax.swing.JLabel lbl_kayitEkrani_oyuncu_1;
    private javax.swing.JLabel lbl_kayitEkrani_oyuncu_2;
    private javax.swing.JLabel lbl_kullaniciadi_1;
    private javax.swing.JLabel lbl_kullaniciadi_2;
    private javax.swing.JLabel lbl_yenidenparola_1;
    private javax.swing.JLabel lbl_yenidenparola_2;
    private javax.swing.JPasswordField txt_KullaniciSifre_kayitEkran_oyuncu_1;
    private javax.swing.JPasswordField txt_KullaniciSifre_kayitEkran_oyuncu_2;
    private javax.swing.JPasswordField txt_KullaniciYenidenSifre_kayitEkran_oyuncu_1;
    private javax.swing.JPasswordField txt_KullaniciYenidenSifre_kayitEkran_oyuncu_2;
    private javax.swing.JTextField txt_adSoyad_oyuncu_1;
    private javax.swing.JTextField txt_adSoyad_oyuncu_2;
    private javax.swing.JTextField txt_kullaniciMAIL_kayitEkran_oyuncu_1;
    private javax.swing.JTextField txt_kullaniciMAIL_kayitEkran_oyuncu_2;
    // End of variables declaration//GEN-END:variables
}
